export const MARKET_TABS = [
  { key: 'daily', label: 'Daily Changes', desc: 'CSE price data' },
  { key: 'overview', label: 'Overview', desc: 'Fundamentals' },
  { key: 'performance', label: 'Performance', desc: 'TradingView returns' },
]

export const COLUMN_GROUPS = {
  daily: [
    { key: 'code', label: 'Company', align: '', px: 'px-4', width: 'w-20' },
    { key: 'name', label: 'Name', align: '', px: 'px-4', width: 'w-32' },
    { key: 'sector', label: 'Sector', align: '', px: 'px-4', width: 'w-24' },
    { key: 'prevClose', label: 'Prev Close', align: 'text-right', px: 'px-4', width: 'w-20' },
    { key: 'open', label: 'Open', align: 'text-right', px: 'px-2', width: 'w-16' },
    { key: 'high', label: 'High', align: 'text-right', px: 'px-2', color: 'emerald', width: 'w-16' },
    { key: 'low', label: 'Low', align: 'text-right', px: 'px-2', color: 'rose', width: 'w-16' },
    { key: 'close', label: 'Close', align: 'text-right', px: 'px-2', width: 'w-16' },
    { key: 'change', label: 'Change', align: 'text-right', px: 'px-4', highlight: true, colorByValue: true, width: 'w-20' },
    { key: 'changePct', label: 'Change %', align: 'text-center', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'range', label: 'Range', align: '', px: 'px-4', width: 'w-20' },
    { key: 'trades', label: 'Trades', align: 'text-right', px: 'px-4', width: 'w-20' },
    { key: 'volume', label: 'Volume', align: 'text-right', px: 'px-4', width: 'w-24' },
    { key: 'to', label: 'Turnover', align: 'text-right', px: 'px-4', last: true, width: 'w-24' },
  ],
  overview: [
    { key: 'code', label: 'Company', align: '', px: 'px-4', width: 'w-20' },
    { key: 'name', label: 'Name', align: '', px: 'px-4', width: 'w-32' },
    { key: 'sector', label: 'Sector', align: '', px: 'px-4', width: 'w-24' },
    { key: 'close', label: 'Close', align: 'text-right', px: 'px-2', width: 'w-16' },
    { key: 'change', label: 'Change', align: 'text-right', px: 'px-4', highlight: true, colorByValue: true, width: 'w-20' },
    { key: 'changePct', label: 'Change %', align: 'text-center', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'mktCap', label: 'Mkt Cap', align: 'text-right', px: 'px-4', width: 'w-20' },
    { key: 'peRatio', label: 'P/E Ratio', align: 'text-right', px: 'px-4', width: 'w-20' },
    { key: 'divYield', label: 'Div Yield', align: 'text-right', px: 'px-4', width: 'w-20' },
    { key: 'to', label: 'Turnover', align: 'text-right', px: 'px-4', width: 'w-24' },
    { key: 'rsi', label: 'RSI', align: 'text-right', px: 'px-4', rsi: true, last: true, width: 'w-16' },
  ],
  performance: [
    { key: 'code', label: 'Company', align: '', px: 'px-4', width: 'w-20' },
    { key: 'name', label: 'Name', align: '', px: 'px-4', width: 'w-32' },
    { key: 'close', label: 'Close', align: 'text-right', px: 'px-2', width: 'w-16' },
    { key: 'changePct', label: 'Today', align: 'text-center', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perf1w', label: '1 Week', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perf1m', label: '1 Month', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perf3m', label: '3 Months', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perf6m', label: '6 Months', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perfYtd', label: 'YTD', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'perf1y', label: '1 Year', align: 'text-right', px: 'px-4', colorByValue: true, width: 'w-20' },
    { key: 'rsi', label: 'RSI', align: 'text-right', px: 'px-4', rsi: true, width: 'w-16' },
    { key: 'recommendation', label: 'Signal', align: 'text-center', px: 'px-4', signal: true, last: true, width: 'w-20' },
  ],
}
